from economy import Economy

economy = Economy(
    id="CZ",
    numeric_id=5,
    # as of May 2015 the following cargos must have fixed positions if used by an economy:
    # passengers: 0, mail: 2, goods 5, food 11
    # keep the rest of the cargos alphabetised
    # bump the min. compatible version if this list changes
    cargos=[
        "passengers",
        "acid",
        "mail",
        "alcohol",
        "alloy_steel",
        "goods",
        "aluminium",
        "ammonia",
        "ammonium_nitrate",
        "bauxite",
        "beans",
        "food",
        "building_materials", 
#        "carbon_steel",
#        "cast_iron",
        "cement",
        "chemicals",
  #       "chlorine",
        "clay",
#        "cleaning_agents",
        "coal",
        "coke",
#        "concrete_products",
		"copper_ore",
        "copper",
#        "copper_concentrate",
        "electrical_parts",
        "electricity",
        "engineering_supplies",
#        "ethylene",
        "farm_supplies",
#        "ferrochrome",
        "fish",
#        "forgings_and_castings",
        "fruits",
        "furniture",
        "glass",
        "grain",
#        "hydrogen",
        "iron_ore",
        "kaolin",
        "limestone",
        "livestock",
        "logs",
        "lumber",
#        "lye",
        "milk",
        "nitrates",
        "oil",
#        "oxygen",
        "packaging",
        "paints_and_coatings",
        "petrol",
        "pig_iron",
#        "pipe",
#        "plant_fibres",
        "plastics",
#        "plastic_parts",
#        "potash",
#        "pyrite_ore",
        "quicklime",
#        "recyclables",
#        "rubber",
#        "salt",
        "sand",
        "scrap_metal",
        "slag",
 #       "soda_ash",
 #       "stainless_steel",
 		"steel",
        "steel_sections",
        "steel_sheet",
        "stone",
		"sugar_beet",
        "sulphur",
        "timber",
        "tyres",
        "vehicle_bodies",
        "vehicle_engines",
        "vehicle_parts",
        "vehicles", 
#        "zinc",
    ],
    industries=["aluminium_plant",                                                   
		"arable_farm",                                                     
		"assembly_plant",                                                 
		"basic_oxygen_furnace",                                           
		"biorefinery",                                                      
		"blast_furnace",                                                    
		"body_plant",                                                        
		"brewery",                                                         
		"brick_works",                                                       
		"builders_yard",                                                     
		"cement_plant",                                                      
		"chemical_plant",                                                    
		"civil_explosives_facility",                                         
		"clay_pit",                                                          
		"coal_mine",                                                         
		"coke_oven",                                                         
		"component_factory",                                                 
		"copper_mine",                                                       
		"copper_refinery",                                                   
		"dairy",                                                             
		"dairy_farm",                                                       
		"engine_plant",                                                      
		"factory_1",                                                         
		"factory_2",                                                         
		"factory_3",                                                         
		"farm",                                                      
		"fish_farm",                                                         
		"flour_mill",                                                        
		"food_market",                                                       
		"food_processor",                                                    
		"forest",                                                            
		"fruit_plantation",                                                  
		"furniture_factory",                                                 
		"general_store",                                                     
		"glass_works",                                                       
		"hardware_store",                                                    
		"hotel",                                                             
		"integrated_steel_mill",                                             
		"iron_ore_mine",                                                     
		"junk_yard",                                                         
		"lime_kiln",                                                         
		"lumber_yard",                                                       
		"machine_shop",                                                      
		"machine_works",                                                     
		"metal_workshop",                                                    
		"oil_refinery",                                                      
		"oil_wells",                                                         
		"orchard_piggery",                                                   
		"paper_mill",                                                        
		"petrol_pump",                                                       
		"plastics_plant",                                                    
		"plaza",                                                             
		"port",                                                              
		"power_plant",                                                       
		"quarry",                                                            
		"sawmill",                                                           
		"sheet_and_pipe_mill",                                               
		"slag_grinding_plant",                                               
		"steel_mill",                                                        
		"stockyard",                                                         
		"sugar_refinery",                                                    
		"supply_yard",                                                       
		"tyre_plant",                                                        
		"vehicle_distributor",                                               
		"vineyard",                                                          
		"wire_and_section_mill",                                                         
        ],
cargoflow_graph_tuning={}
)

